[Scripts]
ollama-windows = """
@echo off
title Ollama Portable
SET "ScriptDir=%~dp0"
set "ARGS=%*"
set OLLAMA_ORIGINS=*
set "PORT=11500"
set "OLLAMA_MODELS=%ScriptDir%\\models"
set "OLLAMA_HOME=%ScriptDir%\\ollama_home"
if not exist "%OLLAMA_MODELS%" mkdir "%OLLAMA_MODELS%"
if not exist "%OLLAMA_HOME%" mkdir "%OLLAMA_HOME%"
set OLLAMA_HOST=127.0.0.1:%PORT%
if "%1"=="serve" (
    "%ScriptDir%\\ollama.exe" serve --port %PORT%
    exit /b
)
%ScriptDir%\\ollama.exe %ARGS%
"""

ollama-unix = """
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ARGS="$@"

export OLLAMA_ORIGINS="*"
PORT=11500
export OLLAMA_MODELS="$SCRIPT_DIR/models"
export OLLAMA_HOME="$SCRIPT_DIR/ollama_home"
export OLLAMA_HOST="127.0.0.1:$PORT"

# Create folders if missing
[ -d "$OLLAMA_MODELS" ] || mkdir -p "$OLLAMA_MODELS"
[ -d "$OLLAMA_HOME" ] || mkdir -p "$OLLAMA_HOME"
=
if [ "$1" = "serve" ]; then
    "$SCRIPT_DIR/bin/ollama" serve --port "$PORT"
    exit 0
fi

"$SCRIPT_DIR/bin/ollama" $ARGS
"""

ollama-macOS = """
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ARGS="$@"

export OLLAMA_ORIGINS="*"
PORT=11500
export OLLAMA_MODELS="$SCRIPT_DIR/models"
export OLLAMA_HOME="$SCRIPT_DIR/ollama_home"
export OLLAMA_HOST="127.0.0.1:$PORT"

# Create folders if missing
[ -d "$OLLAMA_MODELS" ] || mkdir -p "$OLLAMA_MODELS"
[ -d "$OLLAMA_HOME" ] || mkdir -p "$OLLAMA_HOME"
=
if [ "$1" = "serve" ]; then
    "$SCRIPT_DIR/ollama" serve --port "$PORT"
    exit 0
fi

"$SCRIPT_DIR/ollama" $ARGS
"""


[Url-Vars]
pandoc-owner = "jgm"
ollama-owner = "ollama"
archive-types = [".zip", ".tgz", ".tar.gz"]



[Models]

embedding-name = "embeddinggemma-300m"
embedding-pull = "hf.co/second-state/embeddinggemma-300m-GGUF:Q6_K"

llm-name = "Qwen3-VL-2B-Instruct"
llm-pull = "hf.co/unsloth/Qwen3-VL-2B-Instruct-GGUF:Q5_K_M"